### PR TITLE
Change default config to DebugConfig

### PR DESCRIPTION
**Pull request by wallento**
It is required to run make cleanall to update the vivado project and
other artifacts.

### CODE REVIEW

**Comment by wsong83** [comment]
I will have a clean run tomorrow. Hopefully it is just me messed somewhere.

The CONFIG target was setted to disable Debug by default intentionally. I am still pondering about the choice here. Do you consider trace debugger a default part of the SoC or it is a means for debugging when something wrong occurs? Or the argument is this release is a trace debug release so the CONFIG target should enable debug?

**Comment by wallento** [comment]
I think the debug system is a platform feature which is part of the chip. Hence, I would retire any option without debug infrastructure in the long run.

**Comment by asb** [comment]
Does the tracedebug CONFIG currently change the boot method? I think ideally we'd have trace debug always enabled, but have the option to switch between boot-from-SD and boot-via-trace-debugger controlled by e.g. changing one of the many physical switches on the Nexys4

**Comment by wsong83** [comment]
OK. I agree to set debugger enabled by default.
My plan for the final release is to always have a on-chip BRAM so bare-metal examples are always runnable without changing target. Then for the debugger boot process, users just need to have a jump in the BRAM to jump to DDR. There are three ways to do this, providing a very simple jump elf and load it to BRAM using debugger, directly write an instruction to BRAM by debugger, or get a bitstream to have this jump in BRAM. I think button increases maintaining issue as the reset vector is currently automatically controlled by Chisel.

**Comment by wallento** [comment]
Yes, I think this is pretty much in line with what you find in standard SoCs. Maybe the BRAM can contain the bootloader that checks for certain value written somewhere to decide where to boot from.

But, overall the debug part is somewhat orthogonal to the bootloader (at least in theory).

**Pull request merged**
